const body=document.body;const trigger=document.querySelector('#designTrigger');const panel=document.querySelector('#designPanel');const menu=document.querySelector('#menuBtn');const mobile=document.querySelector('#mobileNav');const choices=[...document.querySelectorAll('.design-choice')];const designs=['clyde','beckham','schmidt','breed2','grunt'];
function setDesign(name){if(!designs.includes(name))name='clyde';body.dataset.design=name;localStorage.setItem('amjid-design',name);choices.forEach(b=>b.classList.toggle('active',b.dataset.design===name));const n=designs.indexOf(name)+1;document.querySelector('#designLabel').textContent=`${String(n).padStart(2,'0')} / 05`;document.querySelector('#designCurrent').textContent=name[0].toUpperCase()+name.slice(1);}
setDesign(localStorage.getItem('amjid-design')||'clyde');
trigger?.addEventListener('click',()=>{const open=panel.classList.toggle('open');trigger.setAttribute('aria-expanded',open)});document.addEventListener('click',e=>{if(panel?.classList.contains('open')&&!panel.contains(e.target)&&!trigger.contains(e.target)){panel.classList.remove('open');trigger.setAttribute('aria-expanded','false')}});choices.forEach(b=>b.addEventListener('click',()=>{setDesign(b.dataset.design);panel.classList.remove('open');trigger.setAttribute('aria-expanded','false')}));
menu?.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open)});mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const progress=document.querySelector('.progress');addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${h>0?(scrollY/h)*100:0}%`},{passive:true});
const nav=[...document.querySelectorAll('.nav a')];const sections=[...document.querySelectorAll('main section[id]')];const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>navObserver.observe(s));
const portrait=document.querySelector('.portrait');const supportsFine=matchMedia('(pointer:fine)').matches;if(portrait&&supportsFine){addEventListener('pointermove',e=>{const r=portrait.getBoundingClientRect();const x=(e.clientX-(r.left+r.width/2))/r.width;const y=(e.clientY-(r.top+r.height/2))/r.height;portrait.style.transform=`rotateY(${x*5}deg) rotateX(${-y*5}deg) translateZ(8px)`});addEventListener('pointerleave',()=>portrait.style.transform='')}
const counters=[...document.querySelectorAll('[data-count]')];const countObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting||e.target.dataset.done)return;e.target.dataset.done='1';const target=Number(e.target.dataset.count),suffix=e.target.dataset.suffix||'';let start=0;const t0=performance.now();const tick=t=>{const p=Math.min(1,(t-t0)/1100);start=Math.round(target*(1-Math.pow(1-p,3)));e.target.textContent=start+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}),{threshold:.7});counters.forEach(c=>countObs.observe(c));
const companyButtons=[...document.querySelectorAll('[data-filter]')];const companyCards=[...document.querySelectorAll('[data-company]')];companyButtons.forEach(b=>b.addEventListener('click',()=>{companyButtons.forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;companyCards.forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.company!==f))}));
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
