(()=>{"use strict";
const D={
name:"Muhammad Amjid",email:"amjid.psh@gmail.com",phone:"+92 314 9198403",location:"Peshawar, Pakistan",
photo:"assets/images/Muhammad-Amjid.jpeg",resume:"assets/resume/Muhammad-Amjid-Resume.pdf",
linkedin:"https://www.linkedin.com/in/amjid1988/",github:"https://github.com/AmjidOfficial/",
companies:{
"Aziz Group of Industries":"https://kitepk.com/","Volka Food International (Cookania)":"https://volkafood.com/",
"Ismail Industries Limited":"https://ismailindustries.com.pk/","Muller & Phipps / Shakir & Associates":"https://www.pepsico.com/en/brands/lays"},
jobs:[
["2022 → Present","Regional Sales Manager – North","Aziz Group of Industries","Lead regional FMCG sales operations across North Pakistan, managing 45+ distributors and a field force including 1 Sales Coordinator, 1 ASM, 6 TSMs and 22 Order Bookers. Sales forecasting, demand planning, primary and secondary sales, RTM, distribution and retail execution."],
["Aug 2021 → Mar 2022","FMCG Distributor Operations – Peshawar","FMCG Distributor Operations","Managed FMCG distribution across snacks, biscuits and beverages, secondary sales tracking, retail execution, demand fulfillment and distributor relationships."],
["Jun 2019 → Jul 2021","Zonal Sales Manager – KPK","Volka Food International (Cookania)","Managed zonal sales operations with forecasting, demand planning, RTM execution, distribution expansion, trade marketing and field-force productivity."],
["Feb 2017 → Jun 2019","Area Sales Manager – Peshawar","Ismail Industries Limited","Managed distributor network and General Trade field sales, secondary sales tracking, primary sales execution, merchandising and SKU availability."],
["Jul 2016 → Feb 2017","Area Sales Manager (Acting – KPK)","Ismail Industries Limited","Supervised multiple outstation markets, monitored distributor KPIs, RTM compliance and field training."],
["Feb 2014 → Jun 2016","Territory Sales Manager – Peshawar","Ismail Industries Limited","Managed territory FMCG sales operations, forecasting, demand execution, retail coverage and distributor engagement."],
["Nov 2009 → Feb 2014","Sales Representative – FMCG (PepsiCo Lays)","Muller & Phipps / Shakir & Associates","Executed primary and secondary General Trade sales, retailer relationships, trade promotions and field execution."]],
awards:[
["2025–26","Best Region Award","Regional performance recognition at the Annual Sales Conference 2025–26."],
["5 Sep 2026","Special Recognition (Cash Prize)","Special recognition from Chairman Aziz Group of Industries, Mohsin Aziz Sb."],
["Sep 2026","SalesPulse AI Analytics System Creator","Created SalesPulse in February 2026 using Gemini AI Studio; recognition recorded at the Annual Sales Conference 2025–26."],
["2023–24","Best Regional Sales Manager – National Level","National-level recognition for top regional performance."],
["2023","SMART Sales App Project Lead","Head Office digital transformation initiative for real-time sales tracking, GPS monitoring, attendance and KPI dashboards."],
["2019–20","National Champion ZSM Award","National Champion recognition."],
["2018","Billion Sales Achievement Team","Member of the Billion Sales Achievement Team."]],
education:[["MBA (Executive)","Gomal University","2018–2020"],["MA Islamic Studies","Bacha Khan University","2018"],["BA","University of Peshawar","2015–2016"],["DAE Electrical","BTE KPK","2004–2007"],["SSC","BISE Peshawar","2004"]],
skills:["FMCG Sales Systems","Sales Forecasting Tools","Demand Planning Systems","CRM Platforms","Excel Advanced Reporting","AI-Based Analytics (Gemini AI Studio)","Field Force Tracking Systems","KPI Dashboards","Sales Automation Tools","Numeric Distribution","Weighted Distribution","Retail Execution Excellence","Route-to-Market (RTM) Optimization","Primary Sales Planning","Secondary Sales Tracking","Category Development","Distributor Management","Field Force Leadership","FMCG GT Sales","Sales KPI Management"]};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const ext=(u,t,c="")=>'<a class="'+c+'" href="'+u+'" target="_blank" rel="noopener noreferrer">'+t+'</a>';
const PROFILES=["gravity","editorial","cinematic"],THEMES=["neumorphic","light","dark"];
const META={gravity:["Gravity","Dimensional / structured / interactive"],editorial:["Editorial","Magazine / refined / typographic"],cinematic:["Cinematic","Immersive / dramatic / motion-led"]};
let profile=localStorage.getItem("amjid-profile")||"gravity",theme=localStorage.getItem("amjid-theme")||"neumorphic";
if(!PROFILES.includes(profile))profile="gravity";if(!THEMES.includes(theme))theme="neumorphic";
const save=()=>{localStorage.setItem("amjid-profile",profile);localStorage.setItem("amjid-theme",theme)};
function render(){
document.body.dataset.profile=profile;document.body.dataset.theme=theme;save();
const title=profile==="gravity"?"Sales <span class='outline'>with</span> <span class='accent'>purpose.</span>":profile==="editorial"?"Commercial <span class='outline'>growth</span> <span class='accent'>edited.</span>":"Sales <span class='outline'>×</span> <span class='accent'>technology.</span>";
const profileDesc=META[profile][1];
document.getElementById("app").innerHTML='<div class="app '+profile+'"><div class="grain"></div><header class="nav"><a class="brand" href="#home">AMJID<small>/26</small></a><nav class="navlinks">'+["home","about","focus","work","career","recognition","education","contact"].map((x,i)=>'<a href="#'+x+'">'+["Home","About","Focus","Work","Career","Recognition","Education","Contact"][i]+"</a>").join("")+'</nav><div class="controls"><button class="ctrl" id="profileBtn" aria-expanded="false">Profile</button><button class="ctrl" id="themeBtn" aria-expanded="false">Theme</button></div><button class="menu" id="menu" aria-label="Open menu">☰</button></header><div class="panel" id="panel" aria-hidden="true"></div><div class="profile-ribbon"><span>'+META[profile][0]+"</span><small>"+profileDesc+'</small></div><main>'+
'<section id="home" class="hero"><div class="hero-copy reveal"><div class="eyebrow">MUHAMMAD AMJID · REGIONAL SALES MANAGER · NORTH PAKISTAN</div><h1>'+title+'</h1><p>15+ years in FMCG sales leadership, General Trade, Route-to-Market, distributor management, forecasting, demand planning, field-force leadership and practical digital transformation.</p><div class="chips"><span class="chip">45+ Distributors</span><span class="chip">25% Detergent Share</span><span class="chip">#1 among 6 RSMs</span></div><div class="hero-actions"><a class="hero-link" href="#work">Explore selected work ↗</a><a class="hero-link subtle" href="#contact">Contact me ↗</a></div></div><div class="hero-art reveal"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="card3d"><div class="photo-wrap"><img class="photo" src="'+D.photo+'" alt="Muhammad Amjid" width="390" height="488" fetchpriority="high"></div><div class="card-meta"><span>RSM · NORTH PAKISTAN</span><span>FMCG / 15+ YEARS</span></div></div><div class="float f1">COMMERCIAL<br><b>GROWTH</b></div><div class="float f2">DATA<br><b>DRIVEN</b></div></div></section>'+
'<section id="about" class="section"><div class="section-head"><div class="label">01 / About</div><h2>Commercial growth<br>with <em>field reality.</em></h2></div><div class="two"><p class="lead">I lead FMCG sales operations with a focus on market coverage, distribution, execution and useful numbers.</p><div class="copy">My work connects sales leadership with digital systems. I led the SMART Sales App initiative and created the SalesPulse AI analytics system using Gemini AI Studio. The goal is simple: clearer field information and stronger execution.</div></div><div class="stats"><div class="stat"><b>15+</b><span>Years in FMCG</span></div><div class="stat"><b>45+</b><span>Distributors managed</span></div><div class="stat"><b>25%</b><span>Detergent category share</span></div><div class="stat"><b>#1</b><span>Among 6 RSMs</span></div></div></section>'+
'<section id="focus" class="section"><div class="section-head"><div class="label">02 / Focus</div><h2>For every point<br>of <em>execution.</em></h2></div><div class="grid4">'+[["01","Sales Leadership","Regional strategy, forecasting, target execution, distributor performance and field-force leadership."],["02","RTM & Distribution","Numeric and weighted distribution, route optimization, coverage, availability and retail execution."],["03","Sales Analytics","Brand, SKU, Order Booker and route-level reporting, KPI dashboards and advanced reporting."],["04","Digital Transformation","Sales automation, field-force tracking and practical systems around real field workflows."]].map(x=>'<article class="focus-card reveal"><span class="num">'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div></article>').join("")+'</div></section>'+
'<section id="work" class="section"><div class="section-head"><div class="label">03 / Selected Work</div><h2>Work with<br>a <em>purpose.</em></h2></div><div class="work-grid"><article class="work-card primary reveal"><div><span class="num">01 / SALES TRANSFORMATION</span><h3>SMART<br>SALES</h3><p>Head Office digital transformation initiative for real-time sales tracking, GPS monitoring, attendance and KPI dashboards.</p></div><div class="work-bottom"><span>CASE STUDY</span><button class="work-open" data-case="0">View details ↗</button></div></article><article class="work-card reveal"><div><span class="num">02 / AI ANALYTICS</span><h3>SALESPULSE<br><em>AI</em></h3><p>Brand, SKU, Order Booker and route-level performance analytics created with Gemini AI Studio.</p></div><div class="work-bottom"><span>PRIVATE SYSTEM</span><button class="work-open" data-case="1">View details ↗</button></div></article><article class="work-card gold reveal"><div><span class="num">03 / DIGITAL COMMERCE</span><h3>BAZAR360<br><em>.ONLINE</em></h3><p>Automotive marketplace and showroom ecosystem.</p></div><div class="work-bottom"><span>LIVE</span>'+ext("https://bazar360.online/","Open ↗")+'</div></article></div></section>'+
'<section id="career" class="section"><div class="section-head"><div class="label">04 / Career</div><h2>2009 →<br><em>Present.</em></h2></div><div class="timeline">'+D.jobs.map(j=>'<article class="job reveal"><div class="year">'+esc(j[0])+'</div><div><h3>'+esc(j[1])+'</h3><strong>'+((D.companies[j[2]])?ext(D.companies[j[2]],esc(j[2])):esc(j[2]))+'</strong><p>'+esc(j[3])+'</p></div><div class="type">Experience</div></article>').join("")+'</div></section>'+
'<section id="recognition" class="section"><div class="section-head"><div class="label">05 / Recognition</div><h2>Recognition<br>for <em>impact.</em></h2></div><div class="award-grid">'+D.awards.map(a=>'<article class="award reveal"><strong>'+esc(a[0])+'</strong><div><h3>'+esc(a[1])+'</h3><p>'+esc(a[2])+'</p></div></article>').join("")+'</div></section>'+
'<section id="education" class="section"><div class="section-head"><div class="label">06 / Education</div><h2>Academic<br><em>background.</em></h2></div><div class="edu-grid">'+D.education.map((e,i)=>'<article class="edu reveal"><b>0'+(i+1)+'</b><strong>'+esc(e[0])+'</strong><span>'+esc(e[1])+' · '+esc(e[2])+'</span></article>').join("")+'</div><div class="skills">'+D.skills.map(s=>'<span class="chip">'+esc(s)+'</span>').join("")+'</div></section>'+
'<section id="contact" class="section contact"><div class="section-head"><div class="label">07 / Contact</div><h2>Let’s<br><em>connect.</em></h2></div><div class="contact-grid"><div class="contact-copy"><p>For professional opportunities, sales leadership discussions, digital sales projects or collaboration, use the direct links.</p><div class="contact-links">'+ext("mailto:"+D.email,"Email · "+D.email)+ext("tel:"+D.phone.replace(/\s/g,""),"Call · "+D.phone)+ext(D.linkedin,"LinkedIn · /in/amjid1988")+ext(D.github,"GitHub · @AmjidOfficial")+'<a href="'+D.resume+'">Download Resume ↗</a></div></div><form class="form" id="contactForm"><input name="name" required placeholder="Your name" autocomplete="name"><input name="email" required type="email" placeholder="Your email" autocomplete="email"><textarea name="message" required placeholder="Your message"></textarea><button>Open email draft ↗</button><small class="form-note">Your email app will open with the message ready to send.</small></form></div></section></main><footer class="footer"><span>© 2026 Muhammad Amjid</span><span>Sales · Distribution · Analytics · Digital Transformation</span></footer><div class="modal" id="modal"><div class="modal-card"><button class="modal-close" id="close" aria-label="Close">×</button><div class="label" id="mType"></div><h3 id="mTitle"></h3><p id="mText"></p></div></div></div>';
bind();animate();buildPanel();
}
function togglePanel(kind){const p=document.getElementById("panel"),open=p.classList.contains("open")&&p.dataset.kind===kind;p.dataset.kind=kind;p.classList.toggle("open",!open);p.setAttribute("aria-hidden",open?"true":"false");document.getElementById(kind==="profile"?"profileBtn":"themeBtn")?.setAttribute("aria-expanded",String(!open));buildPanel()}
function buildPanel(){const p=document.getElementById("panel"),kind=p.dataset.kind||"profile";if(!p)return;
if(kind==="profile")p.innerHTML='<div class="panel-title">Choose profile</div>'+PROFILES.map(x=>'<button class="'+(x===profile?"selected":"")+'" data-p="'+x+'"><b>'+META[x][0]+'</b><small>'+META[x][1]+"</small></button>").join("");
else p.innerHTML='<div class="panel-title">Choose theme</div>'+THEMES.map(x=>'<button class="'+(x===theme?"selected":"")+'" data-t="'+x+'"><b>'+({"neumorphic":"Neumorphic","light":"Light","dark":"Dark"}[x])+'</b><small>'+({"neumorphic":"Soft depth / default","light":"Warm editorial paper","dark":"Deep contrast"}[x])+"</small></button>").join("");
p.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{profile=b.dataset.p;closePanels();render()});
p.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{theme=b.dataset.t;closePanels();render()})}
function closePanels(){const p=document.getElementById("panel");if(p){p.classList.remove("open");p.setAttribute("aria-hidden","true")}document.querySelectorAll(".ctrl").forEach(b=>b.setAttribute("aria-expanded","false"))}
function bind(){
const pb=document.getElementById("profileBtn"),tb=document.getElementById("themeBtn"),menu=document.getElementById("menu"),nav=document.querySelector(".navlinks");
pb.onclick=e=>{e.stopPropagation();togglePanel("profile")};tb.onclick=e=>{e.stopPropagation();togglePanel("theme")};
document.addEventListener("click",e=>{const p=document.getElementById("panel");if(p?.classList.contains("open")&&!p.contains(e.target)&&!e.target.closest(".ctrl"))closePanels()},{once:true});
menu.onclick=()=>{nav.classList.toggle("open");menu.textContent=nav.classList.contains("open")?"×":"☰";menu.setAttribute("aria-expanded",String(nav.classList.contains("open")))};
nav.querySelectorAll("a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.querySelectorAll(".work-open").forEach(b=>b.onclick=()=>openCase(+b.dataset.case));
document.getElementById("close").onclick=closeModal;document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closePanels();nav.classList.remove("open");menu.textContent="☰"}});
document.getElementById("contactForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);location.href="mailto:"+D.email+"?subject="+encodeURIComponent("Portfolio contact from "+f.get("name"))+"&body="+encodeURIComponent(f.get("message")+"\n\nEmail: "+f.get("email"))};
const art=document.querySelector(".card3d");if(art&&!matchMedia("(prefers-reduced-motion: reduce)").matches&&matchMedia("(pointer:fine)").matches){const hero=document.querySelector(".hero");hero.onpointermove=e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.setProperty("--mx",(x*34).toFixed(1)+"px");art.style.setProperty("--my",(y*28).toFixed(1)+"px");hero.style.setProperty("--gx",(x*40).toFixed(1)+"px");hero.style.setProperty("--gy",(y*25).toFixed(1)+"px")};hero.onpointerleave=()=>{art.style.setProperty("--mx","0px");art.style.setProperty("--my","0px");hero.style.setProperty("--gx","0px");hero.style.setProperty("--gy","0px")}}
}
function openCase(i){const d=[["SALES TRANSFORMATION","SMART Sales App & Web Portal","Head Office digital transformation system for real-time sales tracking, GPS monitoring, attendance and KPI dashboards."],["AI ANALYTICS","SalesPulse AI Analytics System","AI analytics for Brand, SKU, Order Booker and route-level performance tracking and reporting, created using Gemini AI Studio. The public portfolio intentionally does not expose the private SalesPulse GitHub repository."]][i];document.getElementById("mType").textContent=d[0];document.getElementById("mTitle").textContent=d[1];document.getElementById("mText").textContent=d[2];document.getElementById("modal").classList.add("open")}
function closeModal(){document.getElementById("modal")?.classList.remove("open")}
function animate(){const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches,io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>reduce?x.classList.add("show"):io.observe(x));const sections=[...document.querySelectorAll("section[id]")],links=[...document.querySelectorAll(".navlinks a")],so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-45% 0px -45% 0px"});sections.forEach(s=>so.observe(s))}
render();
})();