(()=>{"use strict";
const DATA={
name:"Muhammad Amjid",email:"amjid.psh@gmail.com",phone:"+92 314 9198403",location:"Peshawar, Pakistan",
photo:"assets/images/Muhammad-Amjid.jpeg",resume:"assets/resume/Muhammad-Amjid-Resume.pdf",
linkedin:"https://www.linkedin.com/in/amjid1988/",github:"https://github.com/AmjidOfficial/",
companies:{
"Aziz Group of Industries":"https://kitepk.com/","Volka Food International (Cookania)":"https://volkafood.com/",
"Ismail Industries Limited":"https://ismailindustries.com.pk/","Muller & Phipps / Shakir & Associates":"https://www.pepsico.com/en/brands/lays"
},
jobs:[
["2022 → Present","Regional Sales Manager – North","Aziz Group of Industries","Mar 2022 – Present. Lead regional FMCG sales operations across North Pakistan, managing 45+ distributors and a field force including 1 Sales Coordinator, 1 ASM, 6 TSMs and 22 Order Bookers. Responsible for sales forecasting, demand planning, primary sales planning and secondary sales tracking. Drive numeric and weighted distribution, RTM optimization, retail penetration, availability, retail execution and merchandising compliance. Spearheaded the SMART Sales App & Web Portal in 2023 for real-time sales tracking, GPS monitoring, attendance and KPI dashboards. Developed SalesPulse AI analytics using Gemini AI Studio for Brand, SKU, Order Booker and route-level performance tracking. Achieved 25% company-wide detergent category share, ranked #1 among 6 Regional Sales Managers."],
["Aug 2021 → Mar 2022","FMCG Distributor Operations – Peshawar","FMCG Distributor Operations","Aug 2021 – Mar 2022. Managed FMCG distribution across snacks, biscuits and beverages. Coordinated secondary sales tracking, demand fulfillment, outlet coverage and product availability across the General Trade network. Maintained distributor relationships, followed market movement and supported numeric distribution expansion and better service levels."],
["Jun 2019 → Jul 2021","Zonal Sales Manager – KPK","Volka Food International (Cookania)","Jun 2019 – Jul 2021. Managed zonal sales operations across KPK, translating sales forecasts and demand plans into field execution. Expanded numeric and weighted distribution, supported RTM improvement, executed trade marketing campaigns, monitored distributor KPIs and worked with the field force to improve productivity and retail execution."],
["Feb 2017 → Jun 2019","Area Sales Manager – Peshawar","Ismail Industries Limited","Feb 2017 – Jun 2019. Managed distributor operations and field sales across General Trade in Peshawar. Planned primary sales, tracked secondary sales, followed outlet coverage and merchandising compliance, and worked with the sales team to improve SKU availability, retail execution and market penetration."],
["Jul 2016 → Feb 2017","Area Sales Manager (Acting – KPK)","Ismail Industries Limited","Supervised multiple outstation markets across KPK while monitoring distributor KPIs, route coverage and RTM execution. Supported field training, market follow-up and sales performance improvement across assigned teams and territories."],
["Feb 2014 → Jun 2016","Territory Sales Manager – Peshawar","Ismail Industries Limited","Feb 2014 – Jun 2016. Managed territory-level FMCG sales operations in General Trade. Used structured sales forecasting, target planning and demand execution to achieve targets. Strengthened outlet coverage, retailer relationships, product availability and distributor engagement."],
["Nov 2009 → Feb 2014","Sales Representative – FMCG (PepsiCo Lays)","Muller & Phipps / Shakir & Associates","Executed primary and secondary sales in General Trade for PepsiCo Lays. Built and maintained retailer relationships, followed outlet availability and visibility, supported trade promotions and carried out day-to-day field execution across the assigned territory."]
]
awards:[
["2025–26","Best Region Award","Company recognition for regional performance."],
["5 Sep 2026","Special Recognition (Cash Prize)","Special recognition from Chairman Aziz Group of Industries, Mohsin Aziz Sb."],
["Sep 2026","SalesPulse AI Analytics System Creator","Created SalesPulse in February 2026 using Gemini AI Studio; recognition was recorded for the Annual Sales Conference 2025–26."],
["2023–24","Best Regional Sales Manager – National Level","National-level recognition for top regional performance."],
["2023","SMART Sales App Project Lead","Head Office digital transformation initiative for real-time sales tracking, GPS monitoring, attendance and KPI dashboards."],
["2019–20","National Champion ZSM Award","National Champion recognition."],
["2018","Billion Sales Achievement Team","Member of the Billion Sales Achievement Team."]
],
education:[["MBA (Executive)","Gomal University","2018–2020"],["MA Islamic Studies","Bacha Khan University","2018"],["BA","University of Peshawar","2015–2016"],["DAE Electrical","BTE KPK","2004–2007"],["SSC","BISE Peshawar","2004"]],
skills:["FMCG Sales Systems","Sales Forecasting Tools","Demand Planning Systems","CRM Platforms","Excel Advanced Reporting","AI-Based Analytics (Gemini AI Studio)","Field Force Tracking Systems","KPI Dashboards","Sales Automation Tools","Numeric Distribution","Weighted Distribution","Retail Execution Excellence","Route-to-Market (RTM) Optimization","Primary Sales Planning","Secondary Sales Tracking","Category Development","Distributor Management","Field Force Leadership","FMCG GT Sales","Sales KPI Management"]
};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const A=(u,t,cls="")=>'<a class="'+cls+'" href="'+u+'" target="_blank" rel="noopener noreferrer">'+t+'</a>';
const get=(k,d)=>localStorage.getItem(k)||d;
const PROFILES=["gravity","editorial","cinematic"], THEMES=["neumorphic","light","dark"];
const DEFAULT_PROFILE="cinematic", DEFAULT_THEME="neumorphic";
function safeStored(key,allowed,fallback){const value=localStorage.getItem(key);return allowed.includes(value)?value:fallback}
function applyState(profile,theme,persist=true){document.body.classList.remove(...PROFILES.map(x=>"profile-"+x),...THEMES.map(x=>"theme-"+x));document.body.classList.add("profile-"+profile,"theme-"+theme);document.body.dataset.profile=profile;document.body.dataset.theme=theme;if(persist){localStorage.setItem("amjid-profile",profile);localStorage.setItem("amjid-theme",theme)}}
function render(){
const profile=safeStored("amjid-profile",PROFILES,DEFAULT_PROFILE),theme=safeStored("amjid-theme",THEMES,DEFAULT_THEME);applyState(profile,theme,true);
document.getElementById("app").innerHTML='<div class="site">'+
'<div class="loading-screen" id="loadingScreen" aria-label="Loading Muhammad Amjid portfolio"><div class="loader-stage"><div class="loader-ring ring-a"></div><div class="loader-ring ring-b"></div><div class="loader-frame"><img src=\"'+DATA.photo+'\" alt="Muhammad Amjid"></div></div><div class="loader-copy">MUHAMMAD AMJID<span>SALES · ANALYTICS · DIGITAL TRANSFORMATION</span></div></div><header class="nav"><a class="logo" href="#home"><img class="brand-pic" src="assets/images/Muhammad-Amjid.jpeg" alt="Muhammad Amjid">Muhammad Amjid</a><nav class="nav-links">'+["home","about","focus","work","career","recognition","education","contact"].map((x,i)=>'<a href="#'+x+'">'+["Home","About","Focus","Work","Career","Recognition","Education","Contact"][i]+"</a>").join("")+'</nav><div class="controls"><button class="pill-btn" id="themeTop">Theme</button><button class="pill-btn" id="profileTop">Profile</button></div><button class="menu" id="menu">☰</button></header>'+
'<div class="toolbar" id="toolbar"></div>'+
'<main>'+
'<section id="home" class="hero"><div class="hero-bg"></div><span class="float-orb orb-a"></span><span class="float-orb orb-b"></span><div class="hero-main reveal"><div class="kicker">'+esc(DATA.name)+' · Regional Sales Manager · North Pakistan</div><h1>Sales <span class="outline">with</span> <span class="accent">purpose.</span></h1><p class="hero-intro">15+ years in FMCG sales leadership, General Trade, Route-to-Market, distributor management, forecasting, demand planning, field force leadership and practical digital transformation.</p><div class="meta"><span class="tag">45+ Distributors</span><span class="tag">25% Detergent Share</span><span class="tag">#1 among 6 RSMs</span></div></div><div class="hero-side reveal"><div class="portrait-wrap"><div class="portrait-card"><img class="portrait" src="'+DATA.photo+'" alt="Muhammad Amjid" width="330" height="413" fetchpriority="high"></div></div><div class="side-note">Peshawar, Pakistan<br>Commercial growth, field execution and sales technology.</div><a class="work-link" href="#work">Explore selected work ↗</a></div></section>'+
'<section id="about" class="section"><div class="section-head"><div class="index">01 / About</div><h2>Commercial growth<br>with <em>field reality.</em></h2></div><div class="two"><p class="lead">I lead FMCG sales operations with a focus on market coverage, distribution, execution and useful numbers.</p><div class="copy">My work connects sales leadership with digital systems. I led the SMART Sales App initiative and created the SalesPulse AI analytics system using Gemini AI Studio. The goal is simple: clearer field information and better execution.</div></div><div class="stats"><div class="stat"><b>15+</b><span>Years in FMCG</span></div><div class="stat"><b>45+</b><span>Distributors managed</span></div><div class="stat"><b>25%</b><span>Detergent category share</span></div><div class="stat"><b>#1</b><span>Among 6 RSMs</span></div></div></section>'+
'<section id="focus" class="section"><div class="section-head"><div class="index">02 / Focus</div><h2>For every point<br>of <em>execution.</em></h2></div><div class="focus-grid">'+[["01","Sales Leadership","Regional strategy, forecasting, target execution, distributor performance and field-force leadership."],["02","RTM & Distribution","Numeric and weighted distribution, route optimization, coverage, availability and retail execution."],["03","Sales Analytics","Brand, SKU, Order Booker and route-level reporting, KPI dashboards and advanced reporting."],["04","Digital Transformation","Sales automation, field-force tracking and practical systems around real field workflows."]].map(x=>'<article class="focus-card reveal"><span>'+x[0]+'</span><div><h3>'+x[1]+'</h3><p>'+x[2]+'</p></div></article>').join("")+'</div></section>'+
'<section id="work" class="section"><div class="section-head"><div class="index">03 / Selected work</div><h2>Work<br>with a <em>purpose.</em></h2></div><div class="work-grid">'+[
["SALES TRANSFORMATION","SMART Sales App & Web Portal","Head office digital transformation initiative for real-time sales tracking, GPS monitoring, attendance and KPI dashboards.","dark"],
["AI ANALYTICS","SalesPulse AI Analytics System","AI analytics for Brand, SKU, Order Booker and route-level performance tracking and reporting. No public repository is displayed.","accent-card"],
["DIGITAL COMMERCE","Bazar360.online","Automotive marketplace platform and online ecosystem.",""]
].map((p,i)=>'<article class="work-card '+p[3]+' reveal"><div><div class="work-top"><span>'+p[0]+'</span><span>0'+(i+1)+'</span></div><h3>'+p[1]+'</h3><p>'+p[2]+'</p></div><div class="work-bottom"><span class="tag">'+(i===2?"LIVE PLATFORM":"CASE STUDY")+'</span>'+(i===2?A("https://bazar360.online/","Open platform ↗","work-link"):'<button class="work-link" data-case="'+i+'">View details ↗</button>')+'</div></article>').join("")+'</div></section>'+
'<section id="career" class="section"><div class="section-head"><div class="index">04 / Career</div><h2>2009 →<br><em>Present.</em></h2></div><div class="timeline">'+DATA.jobs.map((j,i)=>'<article class="job reveal"><div class="year">'+esc(j[0])+'</div><div><h3>'+esc(j[1])+'</h3><strong>'+((DATA.companies[j[2]])?A(DATA.companies[j[2]],esc(j[2])):esc(j[2]))+'</strong><p>'+esc(j[3])+'</p></div><div class="type">Experience</div></article>').join("")+'</div></section>'+
'<section id="recognition" class="section"><div class="section-head"><div class="index">05 / Recognition</div><h2>Recognition<br>for <em>impact.</em></h2></div><div class="award-grid">'+DATA.awards.map(a=>'<article class="award reveal"><strong>'+esc(a[0])+'</strong><div><h3>'+esc(a[1])+'</h3><p>'+esc(a[2])+'</p></div></article>').join("")+'</div></section>'+
'<section id="education" class="section"><div class="section-head"><div class="index">06 / Education</div><h2>Academic<br><em>background.</em></h2></div><div class="edu-grid">'+DATA.education.map((e,i)=>'<article class="edu reveal '+(e[0]==="DAE Electrical"?"edu-highlight":"")+'"><b>0'+(i+1)+'</b><strong>'+esc(e[0])+'</strong><span>'+esc(e[1])+' · '+esc(e[2])+'</span></article>').join("")+'</div><div class="skills"><span class="index">Skills</span>'+DATA.skills.map(s=>'<span class="tag">'+esc(s)+'</span>').join("")+'</div></section>'+
'<section id="contact" class="section contact"><div class="section-head"><div class="index">07 / Contact</div><h2>Let’s<br><em>connect.</em></h2></div><div class="contact-grid"><div class="contact-copy"><p>For professional opportunities, sales leadership discussions, digital sales projects or collaboration, use the direct links.</p><div class="contact-links">'+A("mailto:"+DATA.email,"Email · "+DATA.email)+A(DATA.linkedin,"LinkedIn · /in/amjid1988")+A(DATA.github,"GitHub · @AmjidOfficial")+'<a href="'+DATA.resume+'">Download Resume ↗</a></div></div><form class="contact-form" id="contactForm"><input name="name" required placeholder="Your name"><input name="email" required type="email" placeholder="Your email"><textarea name="message" required placeholder="Your message"></textarea><button>Send message ↗</button></form></div></section>'+
'</main><footer><span>© Muhammad Amjid</span><span>Sales · Distribution · Analytics · Digital Transformation</span></footer>'+
'<div class="modal" id="modal"><div class="modal-card"><button class="modal-close" id="modalClose">×</button><div class="index" id="modalType"></div><h3 id="modalTitle"></h3><p id="modalText"></p><a class="work-link" href="#contact" id="modalAction">Discuss this work ↗</a></div></div></div>';
bind();buildToolbar();animate();setTimeout(()=>document.getElementById("loadingScreen")?.classList.add("loaded"),650);
}
function bind(){
const menu=document.getElementById("menu"),nav=document.querySelector(".nav-links");menu.onclick=()=>{nav.classList.toggle("open");menu.textContent=nav.classList.contains("open")?"×":"☰"};
nav.querySelectorAll("a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
document.getElementById("themeTop").onclick=()=>window.AmjidPortfolio?window.AmjidPortfolio.setTheme(nextTheme()):cycleTheme();document.getElementById("profileTop").onclick=()=>window.AmjidPortfolio?window.AmjidPortfolio.setProfile(nextProfile()):cycleProfile();
document.querySelectorAll("[data-case]").forEach(b=>b.onclick=()=>openCase(+b.dataset.case));
document.getElementById("modalClose").onclick=closeModal;document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
document.getElementById("contactForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);location.href="mailto:"+DATA.email+"?subject="+encodeURIComponent("Portfolio contact from "+f.get("name"))+"&body="+encodeURIComponent(f.get("message")+"\n\nEmail: "+f.get("email"))};
const hero=document.querySelector(".hero");hero.addEventListener("pointermove",e=>{const r=hero.getBoundingClientRect();hero.style.setProperty("--mx",((e.clientX-r.left)/r.width-.5)*80+"px");hero.style.setProperty("--my",((e.clientY-r.top)/r.height-.5)*60+"px")});
}
function openCase(i){const titles=["SMART Sales App & Web Portal","SalesPulse AI Analytics System","Bazar360.online"],texts=["Head office digital transformation system for real-time sales tracking, GPS monitoring, attendance and KPI dashboards.","AI analytics system for Brand, SKU, Order Booker and route-level performance tracking and reporting, created using Gemini AI Studio. No public repository is displayed.","Automotive marketplace platform and online ecosystem."];document.getElementById("modalType").textContent=["SALES TRANSFORMATION","AI ANALYTICS","DIGITAL COMMERCE"][i];document.getElementById("modalTitle").textContent=titles[i];document.getElementById("modalText").textContent=texts[i];document.getElementById("modal").classList.add("open");document.body.style.overflow="hidden"}
function closeModal(){document.getElementById("modal").classList.remove("open");document.body.style.overflow=""}
function animate(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>io.observe(x));const sections=[...document.querySelectorAll("main section[id]")],links=[...document.querySelectorAll(".nav-links a")];const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-45% 0px -45% 0px"});sections.forEach(s=>so.observe(s))}
function buildToolbar(){const t=document.getElementById("toolbar");const profiles=[["gravity","Gravity"],["editorial","Editorial"],["cinematic","Cinematic"]],themes=[["neumorphic","Neumorphic"],["light","Light"],["dark","Dark"]];t.innerHTML=tool("Profile",profiles,"amjid-profile")+" "+tool("Theme",themes,"amjid-theme");t.querySelectorAll("a").forEach(a=>a.onclick=e=>{e.preventDefault();const key=a.dataset.key,id=a.dataset.id;applyState(key==="amjid-profile"?id:document.body.dataset.profile,key==="amjid-theme"?id:document.body.dataset.theme,true);buildToolbar()});t.querySelectorAll(".tool>button").forEach(b=>b.onclick=e=>{e.stopPropagation();const box=b.parentElement;document.querySelectorAll(".tool").forEach(x=>{if(x!==box)x.classList.remove("open")});box.classList.toggle("open")});t.querySelectorAll("[data-key]").forEach(a=>a.setAttribute("aria-current",a.dataset.id===get(a.dataset.key,a.dataset.key==="amjid-profile"?"gravity":"neumorphic")));document.addEventListener("click",()=>document.querySelectorAll(".tool").forEach(x=>x.classList.remove("open")))}
function tool(label,items,key){return '<div class="tool"><button class="pill-btn" type="button">'+label+'⌄</button><div class="tool-menu">'+items.map(x=>'<a href="#" data-key="'+key+'" data-id="'+x[0]+'">'+x[1]+'</a>').join("")+'</div></div>'}
function nextTheme(){const i=THEMES.indexOf(document.body.dataset.theme);return THEMES[(i+1)%THEMES.length]}function nextProfile(){const i=PROFILES.indexOf(document.body.dataset.profile);return PROFILES[(i+1)%PROFILES.length]}function cycleTheme(){applyState(document.body.dataset.profile,nextTheme(),true);buildToolbar()}function cycleProfile(){applyState(nextProfile(),document.body.dataset.theme,true);buildToolbar()}
render();
})();