(()=>{
'use strict';
const DATA={
 name:'Muhammad Amjid', role:'Regional Sales Manager · North Pakistan', location:'Peshawar, Pakistan', years:15, distributors:'45+', structure:'1 CS · 1 ASM · 6 TSM · 22 OBs', share:'25%',
 photo:'assets/images/Muhammad-Amjid.jpeg', resume:'assets/resume/Muhammad-Amjid-Resume.pdf',
 linkedin:'https://www.linkedin.com/in/amjid1988/', github:'https://github.com/AmjidOfficial/', email:'mailto:amjid.psh@gmail.com',
 bazar:'https://bazar360.online/', sales:'https://ais-pre-wno3ve25bj7klf2rzz25gc-54200336767.asia-southeast1.run.app/',
 career:[
  ['2022','PRESENT','Regional Sales Manager – North','Aziz Group of Industries','Mar 2022 – Present',['Lead North Pakistan operations with 45+ distributors and a field structure of 1 CS, 1 ASM, 6 TSMs and 22 OBs.','Own forecasting, demand planning, primary sales, secondary tracking, distribution and RTM optimization.','Led SMART Sales App & Web Portal and created SalesPulse AI analytics for Brand, SKU, OB and route tracking.']],
  ['2021','','FMCG Distributor Operations – Peshawar','Independent distribution role','Aug 2021 – Mar 2022',['Managed snacks, biscuits and beverages distribution, secondary sales tracking, retail execution and demand fulfilment.']],
  ['2019','','Zonal Sales Manager – KPK','Volka Food International (Cookania)','Jun 2019 – Jul 2021',['Managed zonal sales operations, forecasting, demand planning and RTM execution.','Expanded numeric and weighted distribution and improved field-force productivity.']],
  ['2017','','Area Sales Manager – Peshawar','Ismail Industries Limited','Feb 2017 – Jun 2019',['Managed distributor network and General Trade field sales through primary execution, secondary tracking, merchandising and SKU availability.']],
  ['2016','','Area Sales Manager (Acting – KPK)','Ismail Industries Limited','Jul 2016 – Feb 2017',['Supervised multiple outstation markets across KPK and monitored distributor KPIs and RTM compliance.']],
  ['2014','','Territory Sales Manager – Peshawar','Ismail Industries Limited','Feb 2014 – Jun 2016',['Managed territory FMCG sales operations in General Trade and built retail coverage and distributor engagement.']],
  ['2009','','Sales Representative – FMCG (PepsiCo Lays)','Muller & Phipps / Shakir & Associates','Nov 2009 – Feb 2014',['Executed primary and secondary sales, built retailer relationships and supported trade promotions.']]
 ],
 awards:[['2025–26','★','Best Regional Sales Manager','National Level recognition for regional sales performance.'],['2023–24','★','Best Regional Sales Manager','National Level recognition for top regional performance.'],['25% SHARE','#1','Highest Category Share','Detergent category share with company rank #1 among 6 Regional Sales Managers.'],['2019–20','★','National Champion ZSM Award','National Champion recognition.'],['2018','◆','Billion Sales Achievement Team','Member of the Billion Sales Achievement Team.']],
 skills:['Sales Forecasting','Numeric Distribution','Weighted Distribution','RTM Optimization','Distributor Management','Field Force Leadership','Primary & Secondary Sales','Demand Planning','KPI Dashboards','Sales Analytics','AI Analytics','Digital Transformation','General Trade','Route Management','Merchandising','Business Development']
};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const A=(href,label,cls='')=>`<a class="${cls}" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${label}</a>`;
const career=()=>DATA.career.map((x,i)=>`<article class="timeline-item reveal ${i%3?'':'delay1'}"><div class="year">${esc(x[0])}${x[1]?`<small>${esc(x[1])}</small>`:''}</div><div class="dot"></div><div class="job"><span class="role">${i===0?'CURRENT ROLE':'CAREER'}</span><h3>${esc(x[2])}</h3><div class="company">${esc(x[3])}</div><span class="date">${esc(x[4])}</span><ul>${x[5].map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div></article>`).join('');
const awards=()=>DATA.awards.map((x,i)=>`<article class="award ${i===0?'featured':''} reveal delay${(i%3)+1}"><div class="award-icon">${esc(x[1])}</div><span>${esc(x[0])}</span><h3>${esc(x[2])}</h3><p>${esc(x[3])}</p><b>0${i+1}</b></article>`).join('');
const skills=()=>DATA.skills.map(x=>`<span class="skill">${esc(x)}</span>`).join('');
function shell(label){return `<div class="site"><div class="progress" id="progress"></div><div class="cursor-glow" id="cursor-glow"></div><header class="topbar"><a class="brand" href="#top" aria-label="Muhammad Amjid home"><span class="brand-mark">M</span><span>MUHAMMAD<br><b>AMJID</b></span></a><nav class="nav" aria-label="Primary navigation"><a class="active" href="#top">Home</a><a href="#about">About</a><a href="#career">Career</a><a href="#awards">Awards</a><a href="#work">Work</a><a href="#contact">Contact</a></nav><a class="resume" href="${DATA.resume}" target="_blank" rel="noopener">Resume ↗</a><button class="menu" aria-expanded="false" aria-controls="mobile-nav" aria-label="Open navigation"><span></span><span></span></button><nav id="mobile-nav" class="mobile-nav"><a href="#top">Home</a><a href="#about">About</a><a href="#career">Career</a><a href="#awards">Awards</a><a href="#work">Work</a><a href="#contact">Contact</a></nav></header><main id="top"><section class="hero"><div class="hero-grid"><div class="hero-copy reveal"><div class="eyebrow"><i></i>${esc(DATA.role)}</div><p style="margin:55px 0 4px;color:var(--muted);font-size:13px">Hi, I'm</p><h1>Muhammad <span class="gradient">Amjid.</span></h1><p class="hero-lead">Senior FMCG Sales Leader building growth through <strong>sales strategy, distribution, analytics and digital transformation.</strong></p><div class="hero-actions"><a class="btn primary magnetic" href="#work">View my work ↗</a><a class="btn" href="${DATA.resume}" target="_blank" rel="noopener">View resume ↓</a></div><div class="social">${A(DATA.linkedin,'in')}${A(DATA.github,'GH')}${A(DATA.email,'@')}<small>${esc(DATA.location)}</small></div></div><div class="hero-visual reveal delay1"><div class="portrait-wrap" data-tilt><div class="portrait-glow"></div><img class="portrait" src="${DATA.photo}" alt="Muhammad Amjid professional portrait" loading="eager"><div class="profile-chip"><span class="status"></span><div><b>Sales · Strategy · Technology</b><small>Growth leadership with a digital edge</small></div></div></div><div class="float f1"><strong>${DATA.years}+</strong><small>YEARS FMCG</small></div><div class="float f2"><strong>${DATA.share}</strong><small>DET. CATEGORY SHARE</small><em>#1</em></div><div class="orbit o1"></div><div class="orbit o2"></div></div></div><div class="trust wrap"><span>FMCG</span><i></i><span>GENERAL TRADE</span><i></i><span>RTM</span><i></i><span>SALES ANALYTICS</span><i></i><span>DIGITAL TRANSFORMATION</span><i></i><span>AI ANALYTICS</span></div></section>
<section id="about" class="section"><div class="wrap"><div class="section-head"><b>01 / IMPACT</b><span class="section-line"></span><span>MEASURABLE GROWTH</span></div><div class="intro"><div class="reveal"><h2>Passionate about <span class="gradient">commercial excellence.</span></h2></div><div class="reveal delay1"><p class="large">I bring 15+ years of FMCG experience across General Trade, Route-to-Market execution, distributor management, field-force leadership and sales analytics. My focus is simple: <strong>turn market insight into better execution and sustainable growth.</strong></p></div></div><div class="stats"><article class="stat reveal"><strong class="counter" data-target="15">0+</strong><small>Years FMCG experience</small><b>01</b></article><article class="stat reveal delay1"><strong>${DATA.distributors}</strong><small>Distributors led</small><b>02</b></article><article class="stat reveal delay2"><strong style="font-size:clamp(1.15rem,2vw,2rem);line-height:1.1">${DATA.structure}</strong><small>Current North field structure</small><b>03</b></article><article class="stat dark reveal delay3"><strong>${DATA.share}</strong><small>Detergent category share · company rank #1</small><b>04</b></article></div></div></section>
<section id="career" class="section career"><div class="wrap"><div class="section-head"><b>02 / CAREER</b><span class="section-line"></span><span>2009 → PRESENT</span></div><div class="career-head"><h2>A career built<br>around <span class="gradient">growth.</span></h2><p>From Sales Representative to Regional Sales Manager, with experience across territory, area, zonal and regional leadership.</p></div><div class="timeline">${career()}</div></div></section>
<section id="awards" class="section"><div class="wrap"><div class="section-head"><b>03 / RECOGNITION</b><span class="section-line"></span><span>NATIONAL LEVEL</span></div><div class="awards-head"><h2>Recognition that<br><span class="gradient">measures impact.</span></h2><p>Key achievements from a long-term sales career. Each recognition is kept separate and tied to its own period.</p></div><div class="awards-grid">${awards()}</div></div></section>
<section id="work" class="section work"><div class="wrap"><div class="section-head"><b>04 / DIGITAL WORK</b><span class="section-line"></span><span>SALES × TECHNOLOGY</span></div><div class="work-head"><h2>Where sales meets<br><span class="gradient">technology.</span></h2><p>Digital systems created or led around sales tracking, analytics, automation and marketplace commerce.</p></div><div class="work-grid"><article class="work-card light reveal"><span class="num">01</span><div class="work-icon">↗</div><span>SALES TRANSFORMATION</span><h3>SMART Sales App<br>& Web Portal</h3><p>Real-time sales tracking, GPS monitoring, attendance and KPI dashboards for field execution.</p>${A(DATA.sales,'Open project ↗')}</article><article class="work-card reveal delay1"><span class="num">02</span><div class="work-icon">AI</div><span>ANALYTICS</span><h3>SalesPulse<br>AI Analytics</h3><p>Brand, SKU, OB and route-level performance analytics and reporting.</p>${A(DATA.sales,'Open reference ↗')}</article><article class="work-card reveal delay2"><span class="num">03</span><div class="work-icon">B</div><span>AUTOMOTIVE COMMERCE</span><h3>BAZAR360<br><em>.online</em></h3><p>Marketplace work connecting real inventory, showrooms, search, digital media and automotive commerce.</p>${A(DATA.bazar,'Open Bazar360 ↗')}</article><article class="work-card light reveal"><span class="num">04</span><div class="work-icon">▦</div><span>CORE CAPABILITY</span><h3>Sales automation</h3><p>Forecasting · KPI dashboards · field-force tracking · advanced reporting</p></article><article class="work-card light reveal delay1"><span class="num">05</span><div class="work-icon">◎</div><span>CORE CAPABILITY</span><h3>RTM & distribution</h3><p>Numeric distribution · weighted distribution · distributor performance · execution</p></article><article class="work-card light reveal delay2"><span class="num">06</span><div class="work-icon">+</div><span>CORE CAPABILITY</span><h3>Digital transformation</h3><p>Turning field data into simple tools that teams can actually use.</p></article></div></div></section>
<section id="skills" class="section"><div class="wrap"><div class="section-head"><b>05 / CAPABILITY</b><span class="section-line"></span><span>WHAT I BRING</span></div><div class="capabilities"><div class="reveal"><h2>Commercial thinking.<br><span class="gradient">Digital execution.</span></h2></div><div class="skill-cloud reveal delay1">${skills()}</div></div></div></section>
<section id="contact" class="contact"><div class="wrap contact-grid"><div><div class="section-head"><b>06 / CONTACT</b><span class="section-line"></span><span>LET'S CONNECT</span></div><h2>Let's build<br><span class="gradient">what's next.</span></h2></div><div><p>For sales leadership, commercial strategy, digital transformation or business opportunities, reach me directly.</p><div class="contact-links">${A(DATA.email,'Email','')}${A(DATA.linkedin,'LinkedIn','')}${A(DATA.github,'GitHub','')}${A(DATA.bazar,'BAZAR360.online','')}</div></div></div></section></main><footer class="footer"><div class="wrap"><span>© <span id="year"></span> Muhammad Amjid. All rights reserved.</span><span>Portfolio · Design ${label}</span></div></footer><div class="design-dock" aria-label="Portfolio designs"><span>DESIGN</span><button class="design-btn" data-design="1">01</button><button class="design-btn" data-design="2">02</button><button class="design-btn" data-design="3">03</button><button class="design-btn" data-design="4">04</button><button class="design-btn" data-design="5">05</button></div></div>`}
const app=document.getElementById('app');
let current=Number(localStorage.getItem('amjidPortfolioDesign')||1);if(current<1||current>5)current=1;
function render(n){current=n;document.body.className='theme-'+n;app.innerHTML=shell(String(n).padStart(2,'0'));document.title=`Muhammad Amjid | Design ${n}`;document.querySelectorAll('.design-btn').forEach(b=>b.classList.toggle('active',b.dataset.design==n));bind();}
function bind(){
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 document.querySelectorAll('.design-btn').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('amjidPortfolioDesign',b.dataset.design);render(Number(b.dataset.design));window.scrollTo({top:0,behavior:reduce?'auto':'smooth'});}));
 const menu=document.querySelector('.menu'),mobile=document.querySelector('.mobile-nav');if(menu&&mobile){menu.addEventListener('click',()=>{const open=mobile.classList.toggle('open');menu.setAttribute('aria-expanded',open);});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.classList.remove('open');menu.setAttribute('aria-expanded','false');}));}
 const reveal=document.querySelectorAll('.reveal');if(!reduce&&'IntersectionObserver'in window){const ro=new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target);}}),{threshold:.12,rootMargin:'0px 0px -35px'});reveal.forEach(x=>ro.observe(x));}else reveal.forEach(x=>x.classList.add('visible'));
 const counters=document.querySelectorAll('.counter');const animate=el=>{const target=Number(el.dataset.target||0);if(reduce){el.textContent=target+'+';return}const s=performance.now(),d=1000;const f=t=>{const p=Math.min(1,(t-s)/d),e=1-Math.pow(1-p,3);el.textContent=Math.round(target*e)+'+';if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)};if('IntersectionObserver'in window){const co=new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){animate(e.target);o.unobserve(e.target)}}),{threshold:.7});counters.forEach(x=>co.observe(x))}else counters.forEach(animate);
 const nav=[...document.querySelectorAll('.nav a')],sections=[...document.querySelectorAll('main section[id]')];if('IntersectionObserver'in window){const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-40% 0px -52% 0px'});sections.forEach(s=>so.observe(s))}
 const progress=document.getElementById('progress');const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+'%'};addEventListener('scroll',update,{passive:true});update();
 const tilt=document.querySelector('[data-tilt]'),fine=matchMedia('(pointer:fine)').matches;if(tilt&&fine&&!reduce){tilt.addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect(),x=e.clientX/r.width-(r.left/r.width)-.5,y=e.clientY/r.height-(r.top/r.height)-.5;tilt.style.transform=`perspective(900px) rotateY(${x*8}deg) rotateX(${y*-7}deg)`});tilt.addEventListener('pointerleave',()=>tilt.style.transform='')}
 if(fine&&!reduce)document.querySelectorAll('.magnetic').forEach(b=>{b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);b.style.transform=`translate(${x*.07}px,${y*.07}px)`});b.addEventListener('pointerleave',()=>b.style.transform='')});
 const glow=document.getElementById('cursor-glow');if(glow&&fine&&!reduce){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});const loop=()=>{x+=(tx-x)*.1;y+=(ty-y)*.1;glow.style.left=x+'px';glow.style.top=y+'px';requestAnimationFrame(loop)};requestAnimationFrame(loop)}
 document.getElementById('year').textContent=new Date().getFullYear();
}
addEventListener('keydown',e=>{if(['1','2','3','4','5'].includes(e.key)&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){localStorage.setItem('amjidPortfolioDesign',e.key);render(Number(e.key));window.scrollTo({top:0,behavior:'smooth'})}});
render(current);
})();