(()=>{'use strict';
const profiles=[['legacy','01 · Previous Profile'],['editorial','02 · Animated Editorial'],['cinematic','03 · Cinematic Experience']];
const themes=[['neumorphic','01 · Neumorphic'],['light','02 · Light'],['dark','03 · Dark']];
const awards=[
['2025–26','Best Region Award','Company recognition for strong regional sales performance and execution.'],
['SPECIAL','SalesPulse Project Recognition','Special company recognition for the development of the SalesPulse project and its sales analytics work.'],
['SPECIAL','Special Recognition · Cash Prize','Special recognition and cash prize from Chairman Aziz Group of Industries, Mohsin Aziz Sb.'],
['2023–24','Best Regional Sales Manager','National-level recognition for regional sales performance.'],
['2019–20','National Champion ZSM Award','National Champion recognition for zonal sales performance.']
];
function cleanLegacyDuplicate(){document.getElementById('portfolio-recognition')?.remove();const sections=[...document.querySelectorAll('#recognition')];sections.slice(1).forEach(x=>x.remove())}
function modernRecognition(){const root=document.querySelector('.editorial-site,.cinematic-site');if(!root||root.querySelector('.profile-recognition-modern'))return;const prefix=root.classList.contains('editorial-site')?'ev':'cv';const contact=root.querySelector('#ev-contact,#cv-contact');if(!contact)return;const s=document.createElement('section');s.className=`${prefix}-section ${prefix}-recognition-section profile-recognition-modern`;s.id=`${prefix}-recognition`;s.innerHTML=`<div class="${prefix}-index">05 / RECOGNITION</div><div class="${prefix}-recognition-head"><div><span class="${prefix}-number">05</span><h2>Recognition &<br><em>impact.</em></h2></div><p>Selected company and national-level recognition, including SalesPulse project recognition and special leadership recognition.</p></div><div class="${prefix}-award-grid">${awards.map(a=>`<article class="${prefix}-award-card"><span>${a[0]}</span><b>${a[1]}</b><p>${a[2]}</p></article>`).join('')}</div>`;contact.parentNode.insertBefore(s,contact)}
function addCSS(){if(document.getElementById('profile-controls-css'))return;const s=document.createElement('style');s.id='profile-controls-css';s.textContent=`
#profile-theme-control,#profile-switcher-fallback{display:none!important}
#amjid-profile-toolbar{position:fixed;top:12px;right:14px;z-index:2147483000;display:flex;align-items:center;gap:8px;font-family:'DM Mono',monospace;pointer-events:auto}
.amjid-tool{position:relative}
.amjid-tool>button{appearance:none;border:1px solid rgba(127,127,127,.28);background:rgba(255,255,255,.94);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);color:#222;border-radius:999px;padding:10px 13px;min-width:112px;font:700 10px 'DM Mono',monospace;letter-spacing:.05em;cursor:pointer;box-shadow:0 7px 24px rgba(0,0,0,.14);white-space:nowrap;transition:transform .2s ease,box-shadow .2s ease}
.amjid-tool>button:hover,.amjid-tool>button:focus-visible{transform:translateY(-1px);box-shadow:0 10px 28px rgba(0,0,0,.18);outline:2px solid rgba(8,123,120,.25);outline-offset:2px}
.amjid-tool-menu{position:absolute;top:calc(100% + 8px);right:0;width:250px;max-height:min(70vh,420px);overflow:auto;padding:9px;border:1px solid rgba(127,127,127,.2);background:rgba(18,18,18,.97);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-radius:14px;box-shadow:0 18px 50px rgba(0,0,0,.3);display:none}
.amjid-tool.open .amjid-tool-menu{display:block;animation:amjidMenuIn .18s ease}
.amjid-tool-title{color:#888;padding:8px 9px 5px;font:500 8px 'DM Mono',monospace;letter-spacing:.14em}
.amjid-tool-menu a{display:block;color:#ddd;text-decoration:none;padding:11px 9px;border-radius:8px;font:600 10px 'DM Mono',monospace;line-height:1.35}
.amjid-tool-menu a:hover,.amjid-tool-menu a:focus-visible,.amjid-tool-menu a[aria-current="true"]{background:rgba(255,255,255,.1);color:#fff;outline:none}
.amjid-tool-menu a[aria-current="true"]:after{content:'  ✓';color:#c89b57}
.amjid-sidebar-controls{margin-top:14px;padding-top:14px;border-top:1px solid rgba(127,127,127,.18);display:grid;gap:5px}
.amjid-sidebar-title{padding:0 12px 4px;color:#8a8f97;font:800 8px 'DM Mono',monospace;letter-spacing:.12em}
.amjid-sidebar-controls a{display:block;padding:9px 12px;border-radius:10px;color:#6f747c;text-decoration:none;font:600 9px 'DM Mono',monospace}
.amjid-sidebar-controls a:hover,.amjid-sidebar-controls a[aria-current="true"]{background:#f0f4ff;color:#316fe9}
@keyframes amjidMenuIn{from{opacity:0;transform:translateY(-5px)}to{opacity:1;transform:none}}
.source-editorial #amjid-profile-toolbar .amjid-tool>button{background:rgba(245,242,234,.94);color:#171717}
.source-cinematic #amjid-profile-toolbar .amjid-tool>button{background:rgba(18,16,14,.96);color:#f3eee5;border-color:#403a32}
.source-editorial .amjid-sidebar-controls,.source-cinematic .amjid-sidebar-controls{display:none}
@media(max-width:900px){#amjid-profile-toolbar{top:10px;right:10px}.amjid-tool>button{min-width:104px;padding:9px 11px}}
@media(max-width:760px){#amjid-profile-toolbar{left:10px;right:auto;top:10px;gap:6px}.amjid-tool>button{min-width:92px;padding:9px 10px;font-size:9px}.amjid-tool-menu{left:0;right:auto;width:min(245px,calc(100vw - 20px));max-height:60vh}.amjid-tool:last-child .amjid-tool-menu{left:auto;right:0}}
@media(max-width:420px){#amjid-profile-toolbar{left:8px;top:8px;gap:5px}.amjid-tool>button{min-width:86px;padding:8px 9px;font-size:8px}.amjid-tool>button span{font-size:10px}}
@media(prefers-reduced-motion:reduce){.amjid-tool>button,.amjid-tool-menu{transition:none;animation:none}}
`;document.head.appendChild(s)}
function linkFor(kind,id){const u=new URL(location.href);u.search='';u.hash='';const p=localStorage.getItem('amjid-profile-mode')||'legacy';const t=localStorage.getItem('amjid-theme')||'neumorphic';u.searchParams.set('profile',kind==='profile'?id:p);u.searchParams.set('theme',kind==='theme'?id:t);return u.href}
function markCurrent(root){const p=localStorage.getItem('amjid-profile-mode')||'legacy';const t=localStorage.getItem('amjid-theme')||'neumorphic';root.querySelectorAll('[data-profile]').forEach(a=>a.setAttribute('aria-current',String(a.dataset.profile===p)));root.querySelectorAll('[data-theme]').forEach(a=>a.setAttribute('aria-current',String(a.dataset.theme===t)))}
function buildTool(kind,items,title){const box=document.createElement('div');box.className='amjid-tool';const label=kind==='profile'?'Profile':'Theme';box.innerHTML=`<button type="button" aria-expanded="false">${label} <span aria-hidden="true">⌄</span></button><div class="amjid-tool-menu"><div class="amjid-tool-title">${title}</div>${items.map(([id,text])=>`<a data-${kind}="${id}" href="${linkFor(kind,id)}">${text}</a>`).join('')}</div>`;const btn=box.querySelector('button');btn.addEventListener('click',e=>{e.stopPropagation();const bar=box.parentElement;bar.querySelectorAll('.amjid-tool').forEach(x=>{if(x!==box){x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')}});const open=box.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))});return box}
function makeToolbar(){let bar=document.getElementById('amjid-profile-toolbar');if(!bar){addCSS();bar=document.createElement('div');bar.id='amjid-profile-toolbar';bar.setAttribute('role','group');bar.setAttribute('aria-label','Profile and theme controls');bar.append(buildTool('profile',profiles,'CHANGE PROFILE'),buildTool('theme',themes,'CHANGE THEME'));document.body.appendChild(bar);bar.addEventListener('click',e=>e.stopPropagation())}else{const links=bar.querySelectorAll('a');links.forEach(a=>{const kind=a.dataset.profile?'profile':'theme';const id=a.dataset.profile||a.dataset.theme;a.href=linkFor(kind,id)})}markCurrent(bar)}
function makeSidebarControls(){const side=document.querySelector('.sidebar');if(!side||side.querySelector('.amjid-sidebar-controls'))return;const box=document.createElement('div');box.className='amjid-sidebar-controls';box.innerHTML=`<div class="amjid-sidebar-title">PROFILE & THEME</div><a href="#" data-profile-menu>Change Profile</a><a href="#" data-theme-menu>Change Theme</a>`;const bottom=side.querySelector('.side-bottom');side.insertBefore(box,bottom||null);box.querySelector('[data-profile-menu]').addEventListener('click',e=>{e.preventDefault();document.querySelector('#amjid-profile-toolbar [data-profile="'+(localStorage.getItem('amjid-profile-mode')||'legacy')+'"]')?.focus();document.querySelector('#amjid-profile-toolbar .amjid-tool:first-child button')?.click()});box.querySelector('[data-theme-menu]').addEventListener('click',e=>{e.preventDefault();document.querySelector('#amjid-profile-toolbar .amjid-tool:last-child button')?.click()})}
function ensureControls(){makeToolbar();makeSidebarControls();const old=document.getElementById('profile-switcher-fallback');if(old)old.remove();const oldMenu=document.getElementById('profile-switcher-fallback-menu');if(oldMenu)oldMenu.remove()}
function run(){cleanLegacyDuplicate();modernRecognition();ensureControls()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,120),{once:true});else setTimeout(run,120);new MutationObserver(()=>{if(!document.getElementById('amjid-profile-toolbar'))setTimeout(run,20)}).observe(document.body,{childList:true});
})();