(()=>{'use strict';
const profiles=[['legacy','01 · Previous Profile'],['editorial','02 · Animated Editorial'],['cinematic','03 · Cinematic Experience']];
const themes=[['neumorphic','01 · Neumorphic'],['light','02 · Light'],['dark','03 · Dark']];
const awards=[
['2025–26','Best Region Award','Company recognition for strong regional sales performance and execution.'],
['SPECIAL','SalesPulse Project Recognition','Special company recognition for the development of the SalesPulse project and its sales analytics work.'],
['SPECIAL','Special Recognition · Cash Prize','Special recognition and cash prize from Chairman Aziz Group of Industries, Mohsin Aziz Sb.'],
['2023–24','Best Regional Sales Manager','National-level recognition for regional sales performance.'],
['2019–20','National Champion ZSM Award','National Champion recognition for zonal sales performance.']
];
function cleanLegacyDuplicate(){const extra=document.getElementById('portfolio-recognition');if(extra)extra.remove();const sections=[...document.querySelectorAll('#recognition')];sections.slice(1).forEach(x=>x.remove())}
function modernRecognition(){const root=document.querySelector('.editorial-site,.cinematic-site');if(!root||root.querySelector('.profile-recognition-modern'))return;const prefix=root.classList.contains('editorial-site')?'ev':'cv';const contact=root.querySelector('#ev-contact,#cv-contact');if(!contact)return;const s=document.createElement('section');s.className=`${prefix}-section ${prefix}-recognition-section profile-recognition-modern`;s.id=`${prefix}-recognition`;s.innerHTML=`<div class="${prefix}-index">05 / RECOGNITION</div><div class="${prefix}-recognition-head"><div><span class="${prefix}-number">05</span><h2>Recognition &<br><em>impact.</em></h2></div><p>Selected company and national-level recognition, including SalesPulse project recognition and special leadership recognition.</p></div><div class="${prefix}-award-grid">${awards.map(a=>`<article class="${prefix}-award-card"><span>${a[0]}</span><b>${a[1]}</b><p>${a[2]}</p></article>`).join('')}</div>`;contact.parentNode.insertBefore(s,contact)}
function addToolbarCSS(){if(document.getElementById('profile-toolbar-css'))return;const s=document.createElement('style');s.id='profile-toolbar-css';s.textContent=`
#profile-theme-control,#profile-switcher-fallback{display:none!important}
#amjid-profile-toolbar{position:fixed;top:14px;right:18px;z-index:100000;display:flex;align-items:center;gap:8px;font-family:'DM Mono',monospace}
.amjid-tool{position:relative}
.amjid-tool>button{appearance:none;border:1px solid rgba(127,127,127,.28);background:rgba(255,255,255,.88);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);color:#222;border-radius:999px;padding:10px 13px;min-width:112px;font:600 10px 'DM Mono',monospace;letter-spacing:.05em;cursor:pointer;box-shadow:0 7px 24px rgba(0,0,0,.12)}
.amjid-tool>button:hover{transform:translateY(-1px)}
.amjid-tool-menu{position:absolute;top:calc(100% + 8px);right:0;width:230px;padding:9px;border:1px solid rgba(127,127,127,.2);background:rgba(18,18,18,.96);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-radius:14px;box-shadow:0 18px 50px rgba(0,0,0,.3);display:none}
.amjid-tool.open .amjid-tool-menu{display:block;animation:amjidMenuIn .18s ease}
.amjid-tool-title{color:#888;padding:8px 9px 5px;font:500 8px 'DM Mono',monospace;letter-spacing:.14em}
.amjid-tool-menu a{display:block;color:#ddd;text-decoration:none;padding:10px 9px;border-radius:8px;font:500 10px 'DM Mono',monospace}
.amjid-tool-menu a:hover,.amjid-tool-menu a[aria-current="true"]{background:rgba(255,255,255,.1);color:#fff}
.amjid-tool-menu a[aria-current="true"]:after{content:'  ✓';color:#c89b57}
@keyframes amjidMenuIn{from{opacity:0;transform:translateY(-5px)}to{opacity:1;transform:none}}
.source-editorial #amjid-profile-toolbar .amjid-tool>button{background:rgba(245,242,234,.9);color:#171717}
.source-cinematic #amjid-profile-toolbar .amjid-tool>button{background:rgba(18,16,14,.9);color:#f3eee5;border-color:#403a32}
@media(max-width:760px){#amjid-profile-toolbar{top:10px;right:10px;left:10px;justify-content:flex-end}.amjid-tool>button{min-width:0;padding:9px 11px}.amjid-tool-menu{right:0;width:210px}}
`;document.head.appendChild(s)}
function linkFor(kind,id){const p=localStorage.getItem('amjid-profile-mode')||'legacy';const t=localStorage.getItem('amjid-theme')||'neumorphic';return `?profile=${kind==='profile'?id:p}&theme=${kind==='theme'?id:t}`}
function makeToolbar(){if(document.getElementById('amjid-profile-toolbar'))return;addToolbarCSS();const bar=document.createElement('div');bar.id='amjid-profile-toolbar';const profileBox=document.createElement('div');profileBox.className='amjid-tool';profileBox.innerHTML=`<button type="button" aria-expanded="false">Profile <span>⌄</span></button><div class="amjid-tool-menu"><div class="amjid-tool-title">CHANGE PROFILE</div>${profiles.map(([id,label])=>`<a data-profile="${id}" href="${linkFor('profile',id)}">${label}</a>`).join('')}</div>`;const themeBox=document.createElement('div');themeBox.className='amjid-tool';themeBox.innerHTML=`<button type="button" aria-expanded="false">Theme <span>⌄</span></button><div class="amjid-tool-menu"><div class="amjid-tool-title">CHANGE THEME</div>${themes.map(([id,label])=>`<a data-theme="${id}" href="${linkFor('theme',id)}">${label}</a>`).join('')}</div>`;bar.append(profileBox,themeBox);document.body.appendChild(bar);const boxes=[profileBox,themeBox];boxes.forEach(box=>{const btn=box.querySelector('button');btn.addEventListener('click',e=>{e.stopPropagation();boxes.forEach(x=>{if(x!==box){x.classList.remove('open');x.querySelector('button').setAttribute('aria-expanded','false')}});const open=box.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))})});document.addEventListener('click',()=>boxes.forEach(box=>{box.classList.remove('open');box.querySelector('button').setAttribute('aria-expanded','false')}),{passive:true});bar.addEventListener('click',e=>e.stopPropagation());bar.querySelectorAll('a[data-profile],a[data-theme]').forEach(a=>a.addEventListener('click',()=>{if(a.dataset.profile)localStorage.setItem('amjid-profile-mode',a.dataset.profile);if(a.dataset.theme)localStorage.setItem('amjid-theme',a.dataset.theme)}));const currentP=localStorage.getItem('amjid-profile-mode')||'legacy';const currentT=localStorage.getItem('amjid-theme')||'neumorphic';bar.querySelector(`[data-profile="${currentP}"]`)?.setAttribute('aria-current','true');bar.querySelector(`[data-theme="${currentT}"]`)?.setAttribute('aria-current','true')}
function ensureControl(){makeToolbar();const b=document.getElementById('profile-theme-control');if(b)b.style.display='none';const old=document.getElementById('profile-switcher-fallback');if(old)old.remove();const oldMenu=document.getElementById('profile-switcher-fallback-menu');if(oldMenu)oldMenu.remove()}
function run(){cleanLegacyDuplicate();modernRecognition();ensureControl()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,80),{once:true});else setTimeout(run,80);new MutationObserver(()=>setTimeout(run,30)).observe(document.body,{childList:true});
})();