(()=>{
'use strict';
const A=(u,t,c='')=>`<a class="${c}" href="${u}" target="_blank" rel="noopener">${t}</a>`;
const D={name:'Muhammad Amjid',photo:'assets/images/Muhammad-Amjid.jpeg',resume:'assets/resume/Muhammad-Amjid-Resume.pdf',email:'amjid.psh@gmail.com',linkedin:'https://www.linkedin.com/in/amjid1988/',github:'https://github.com/AmjidOfficial/',bazar:'https://bazar360.online/'};
const jobs=[
['2022','Present','Regional Sales Manager – North','Aziz Group of Industries','Lead North Pakistan operations, distributor performance, forecasting, demand planning, RTM and digital sales transformation.'],
['2019','2021','Zonal Sales Manager – KPK','Volka Food International (Cookania)','Managed zonal sales operations, distributor network, field execution and market growth.'],
['2017','2019','Area Sales Manager – Peshawar','Ismail Industries Limited','Managed General Trade sales, distribution, SKU availability and field-force execution.'],
['2014','2017','Territory / Acting Area Sales Manager','Ismail Industries Limited','Built territory coverage, distributor engagement and retail execution across KPK.'],
['2009','2014','Sales Representative – FMCG','Muller & Phipps / Shakir & Associates','Executed primary and secondary sales and developed retailer relationships.']
];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(){document.getElementById('app').innerHTML=`
<div class="page-shell">
<aside class="sidebar" id="sidebar">
 <a class="side-logo" href="#home"><span>MA</span><b>Muhammad<br>Amjid</b></a>
 <nav><a class="active" href="#home">Home</a><a href="#about">About</a><a href="#services">What I Do</a><a href="#career">Experience</a><a href="#projects">Projects</a><a href="#recognition">Recognition</a><a href="#contact">Contact</a></nav>
 <div class="side-bottom">${A(D.linkedin,'LinkedIn')} ${A(D.github,'GitHub')}</div>
</aside>
<button class="mobile-menu" aria-label="Open menu">☰</button>
<main class="content">
<section id="home" class="hero panel">
 <div class="hero-copy reveal"><div class="pill">● AVAILABLE FOR NEW OPPORTUNITIES</div><p class="hi">Hi, I'm</p><h1>Muhammad <span>Amjid</span></h1><p class="lead">I build <b>commercial growth</b> through professional sales, distribution excellence, analytics and digital transformation.</p><div class="actions">${A('#projects','View My Work ↗','btn primary')}${A(D.resume,'Resume ↓','btn')}</div><div class="mini-social">${A(D.linkedin,'in')}${A(D.github,'GH')}${A(D.email,'@')}</div></div>
 <div class="hero-art reveal delay"><div class="halo"></div><div class="card3d"><div class="card-top"><span>MUHAMMAD AMJID</span><small>RSM · NORTH PAKISTAN</small></div><img src="${D.photo}" alt="Muhammad Amjid"><div class="card-info"><b>Sales Professional</b><span>15+ Years FMCG Experience</span></div><div class="card-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="float f-left"><b>45+</b><span>Distributors</span></div><div class="float f-right"><b>25%</b><span>Category Share · #1</span></div><div class="spark s1"></div><div class="spark s2"></div></div>
</section>
<div class="ticker"><span>FMCG</span><i>✦</i><span>SALES PROFESSIONAL</span><i>✦</i><span>RTM</span><i>✦</i><span>SALES ANALYTICS</span><i>✦</i><span>DIGITAL TRANSFORMATION</span><i>✦</i><span>FMCG</span></div>
<section id="about" class="section"><div class="section-title"><small>01 / ABOUT</small><span></span><small>THE PERSON BEHIND THE NUMBERS</small></div><div class="about-grid"><div class="reveal"><h2>Building growth with <em>purpose.</em></h2></div><div class="reveal delay"><p>I am an FMCG sales professional with <b>15+ years</b> of experience across General Trade, Route-to-Market, distributor management, forecasting, demand planning and field execution.</p><p>My approach is practical: understand the market, simplify the numbers, improve execution and make the team faster.</p></div></div><div class="stats"><div><b data-count="15">0+</b><span>Years FMCG</span></div><div><b data-count="45">0+</b><span>Distributors managed</span></div><div><b data-count="25">0%</b><span>Detergent category share</span></div><div><b>#1</b><span>Company rank in category</span></div></div></section>
<section id="services" class="section services"><div class="section-title"><small>02 / WHAT I DO</small><span></span><small>COMMERCIAL EXCELLENCE</small></div><div class="center-title"><h2>What I <em>Do</em></h2><p>Delivering practical solutions across the full lifecycle of professional sales operations.</p></div><div class="service-grid"><article class="service active reveal"><span>⌁</span><h3>Sales Strategy & Execution</h3><p>Regional strategy, target setting, distributor performance, team coordination and market execution.</p><b>01</b></article><article class="service reveal"><span>◌</span><h3>RTM & Distribution</h3><p>Numeric and weighted distribution, route optimization, outlet coverage and execution quality.</p><b>02</b></article><article class="service reveal"><span>◈</span><h3>Sales Analytics</h3><p>KPI dashboards, Brand, SKU, OB and route analytics that turn field data into action.</p><b>03</b></article><article class="service reveal"><span>▦</span><h3>Digital Transformation</h3><p>Simple digital systems for sales tracking, reporting, attendance and field-force productivity.</p><b>04</b></article></div></section>
<section id="career" class="section career"><div class="section-title"><small>03 / EXPERIENCE</small><span></span><small>2009 → PRESENT</small></div><div class="center-title"><h2>A career built around <em>growth.</em></h2></div><div class="timeline">${jobs.map((j,i)=>`<article class="job reveal"><div class="job-year">${j[0]}<small>${j[1]}</small></div><div class="job-dot"></div><div class="job-card"><small>${i?'CAREER':'CURRENT ROLE'}</small><h3>${esc(j[2])}</h3><b>${esc(j[3])}</b><p>${esc(j[4])}</p></div></article>`).join('')}</div></section>
<section id="projects" class="section projects"><div class="section-title"><small>04 / PROJECTS</small><span></span><small>SALES × TECHNOLOGY</small></div><div class="project-grid"><article class="project big reveal"><small>01 · SALES TRANSFORMATION</small><h3>SMART Sales App<br>& Web Portal</h3><p>Real-time sales tracking, GPS monitoring, attendance and KPI dashboards.</p>${A('https://ais-pre-wno3ve25bj7klf2rzz25gc-54200336767.asia-southeast1.run.app/','Open Project ↗')}</article><article class="project reveal"><small>02 · AI ANALYTICS</small><h3>SalesPulse<br>AI Analytics</h3><p>Brand, SKU, OB and route-level performance analytics.</p>${A('https://ais-pre-wno3ve25bj7klf2rzz25gc-54200336767.asia-southeast1.run.app/','View ↗')}</article><article class="project blue reveal"><small>03 · AUTOMOTIVE COMMERCE</small><h3>BAZAR360<br><em>.online</em></h3><p>Automotive marketplace and showroom ecosystem.</p>${A(D.bazar,'Open Bazar360 ↗')}</article></div></section>
<section id="recognition" class="section recognition"><div class="section-title"><small>05 / RECOGNITION</small><span></span><small>NATIONAL LEVEL</small></div><div class="center-title"><h2>Recognition that measures <em>impact.</em></h2></div><div class="award-row"><article><strong>2025–26</strong><h3>Best Regional Sales Manager</h3><p>National Level recognition for regional sales performance.</p></article><article><strong>2023–24</strong><h3>Best Regional Sales Manager</h3><p>National Level recognition for top regional performance.</p></article><article><strong>2019–20</strong><h3>National Champion ZSM Award</h3><p>National Champion recognition.</p></article></div></section>
<section id="contact" class="section contact"><div class="section-title"><small>06 / CONTACT</small><span></span><small>LET'S CONNECT</small></div><div class="contact-box"><div><h2>Let's <em>Connect</em></h2><p>Currently open for new opportunities and meaningful collaborations. Whether you have a question or want to say hi, I'll try my best to get back to you.</p><div class="contact-list">${A(D.email,'✉  '+D.email)}${A(D.linkedin,'in  LinkedIn Profile')}${A(D.github,'◉  GitHub Profile')}</div></div><form id="contact-form"><input required name="name" placeholder="Your Name"><input required type="email" name="email" placeholder="Your Email"><textarea required name="message" placeholder="Message"></textarea><button>Send Message ↗</button></form></div></section>
<footer><span>© ${new Date().getFullYear()} Muhammad Amjid</span><span>Built with strategy, data & technology.</span></footer>
</main><div class="bottom-nav"><a href="#home">⌂<small>Home</small></a><a href="#about">◎<small>About</small></a><a href="#services">✦<small>Work</small></a><a href="#projects">▣<small>Projects</small></a><a href="#contact">✉<small>Contact</small></a></div>
</div>`;bind()}
function bind(){
 const menu=document.querySelector('.mobile-menu'),side=document.querySelector('.sidebar');menu.onclick=()=>{side.classList.toggle('open');menu.textContent=side.classList.contains('open')?'×':'☰'};
 const els=document.querySelectorAll('.reveal');const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)els.forEach(e=>e.classList.add('show'));else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e))}
 const counters=document.querySelectorAll('[data-count]');const co=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const t=+e.target.dataset.count,s=performance.now();const f=n=>{const p=Math.min(1,(n-s)/900);e.target.textContent=Math.round(t*(1-Math.pow(1-p,3)))+(t===25?'%':'+');if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f);co.unobserve(e.target)}}));counters.forEach(e=>co.observe(e));
 const sections=[...document.querySelectorAll('section[id]')],links=[...document.querySelectorAll('.sidebar nav a')];const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-42% 0px -50% 0px'});sections.forEach(s=>so.observe(s));
 document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>side.classList.remove('open')));
 const art=document.querySelector('.card3d');if(art&&!reduce&&matchMedia('(pointer:fine)').matches){document.querySelector('.hero-art').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.transform=`perspective(900px) rotateY(${x*14}deg) rotateX(${y*-12}deg) translateY(${y*-8}px)`});document.querySelector('.hero-art').addEventListener('pointerleave',()=>art.style.transform='')}
 document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);location.href=`mailto:${D.email}?subject=Portfolio%20Contact%20from%20${encodeURIComponent(f.get('name'))}&body=${encodeURIComponent(f.get('message')+'\n\nEmail: '+f.get('email'))}`});
}
render();
})();