(()=>{'use strict';
const profiles=[['legacy','01 · Previous Profile'],['editorial','02 · Animated Editorial'],['cinematic','03 · Cinematic Experience']];
const themes=[['neumorphic','01 · Neumorphic'],['light','02 · Light'],['dark','03 · Dark']];
const awards=[
['2025–26','Best Region Award','Company recognition for strong regional sales performance and execution.'],
['SPECIAL','SalesPulse Project Recognition','Special company recognition for the development of the SalesPulse project and its sales analytics work.'],
['SPECIAL','Special Recognition · Cash Prize','Special recognition and cash prize from Chairman Aziz Group of Industries, Mohsin Aziz Sb.'],
['2023–24','Best Regional Sales Manager','National-level recognition for regional sales performance.'],
['2019–20','National Champion ZSM Award','National Champion recognition for zonal sales performance.']
];
function cleanLegacyDuplicate(){const extra=document.getElementById('portfolio-recognition');if(extra)extra.remove();const sections=[...document.querySelectorAll('#recognition')];sections.slice(1).forEach(x=>x.remove())}
function modernRecognition(){const root=document.querySelector('.editorial-site,.cinematic-site');if(!root||root.querySelector('.profile-recognition-modern'))return;const prefix=root.classList.contains('editorial-site')?'ev':'cv';const contact=root.querySelector('#ev-contact,#cv-contact');if(!contact)return;const s=document.createElement('section');s.className=`${prefix}-section ${prefix}-recognition-section profile-recognition-modern`;s.id=`${prefix}-recognition`;s.innerHTML=`<div class="${prefix}-index">05 / RECOGNITION</div><div class="${prefix}-recognition-head"><div><span class="${prefix}-number">05</span><h2>Recognition &<br><em>impact.</em></h2></div><p>Selected company and national-level recognition, including SalesPulse project recognition and special leadership recognition.</p></div><div class="${prefix}-award-grid">${awards.map(a=>`<article class="${prefix}-award-card"><span>${a[0]}</span><b>${a[1]}</b><p>${a[2]}</p></article>`).join('')}</div>`;contact.parentNode.insertBefore(s,contact)}
function ensureControl(){const b=document.getElementById('profile-theme-control');if(b){b.style.zIndex='100000';b.setAttribute('aria-label','Change profile or theme');return}const button=document.createElement('button');button.id='profile-switcher-fallback';button.textContent='Change Profile';Object.assign(button.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:'100000',border:'1px solid rgba(127,127,127,.3)',background:'rgba(255,255,255,.9)',color:'#222',borderRadius:'999px',padding:'11px 15px',font:'600 10px monospace',cursor:'pointer',boxShadow:'0 8px 30px rgba(0,0,0,.15)'});const menu=document.createElement('div');menu.id='profile-switcher-fallback-menu';Object.assign(menu.style,{position:'fixed',right:'18px',bottom:'66px',zIndex:'100001',width:'245px',padding:'12px',background:'rgba(18,18,18,.96)',borderRadius:'16px',boxShadow:'0 18px 50px rgba(0,0,0,.3)',display:'none'});const title=t=>{const d=document.createElement('div');d.textContent=t;Object.assign(d.style,{color:'#888',font:'500 9px monospace',letterSpacing:'.12em',padding:'8px'});return d};menu.append(title('PROFILE OPTIONS'));profiles.forEach(([id,label])=>{const a=document.createElement('a');a.textContent=label;a.href=`?profile=${id}&theme=${localStorage.getItem('amjid-theme')||'neumorphic'}`;Object.assign(a.style,{display:'block',color:'#ddd',textDecoration:'none',padding:'10px 8px',font:'500 10px monospace',borderRadius:'8px'});menu.append(a)});menu.append(title('THEME'));themes.forEach(([id,label])=>{const a=document.createElement('a');a.textContent=label;a.href=`?profile=${localStorage.getItem('amjid-profile-mode')||'legacy'}&theme=${id}`;Object.assign(a.style,{display:'block',color:'#ddd',textDecoration:'none',padding:'10px 8px',font:'500 10px monospace',borderRadius:'8px'});menu.append(a)});document.body.append(button,menu);button.onclick=()=>menu.style.display=menu.style.display==='none'?'block':'none'}
function run(){cleanLegacyDuplicate();modernRecognition();ensureControl()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,80),{once:true});else setTimeout(run,80);new MutationObserver(()=>setTimeout(run,30)).observe(document.body,{childList:true});
})();