"use client";
import {useState} from "react";
import {motion} from "framer-motion";
import {LoadingScreen} from "./LoadingScreen";
import {Scene} from "./Scene";
import {useTheme} from "./ThemeProvider";
const img="https://amjidofficial.github.io/Profile/assets/images/Muhammad-Amjid.jpeg";
const resume="https://amjidofficial.github.io/Profile/assets/resume/Muhammad-Amjid-Resume.pdf";
const jobs=[["2022 → Present","Regional Sales Manager – North","Aziz Group of Industries","https://kitepk.com/"],["Aug 2021 → Mar 2022","FMCG Distributor Operations – Peshawar","FMCG Distributor Operations",""],["Jun 2019 → Jul 2021","Zonal Sales Manager – KPK","Volka Food International (Cookania)","https://volkafood.com/"],["Feb 2017 → Jun 2019","Area Sales Manager – Peshawar","Ismail Industries Limited","https://ismailindustries.com.pk/"],["Jul 2016 → Feb 2017","Area Sales Manager (Acting – KPK)","Ismail Industries Limited","https://ismailindustries.com.pk/"],["Feb 2014 → Jun 2016","Territory Sales Manager – Peshawar","Ismail Industries Limited","https://ismailindustries.com.pk/"],["Nov 2009 → Feb 2014","Sales Representative – FMCG (PepsiCo Lays)","Muller & Phipps / Shakir & Associates","https://www.pepsico.com/"]];
const awards=[["2025–26","Best Region Award","Company recognition for regional performance."],["5 Sep 2026","Special Recognition · Cash Prize","Special recognition from Chairman Aziz Group of Industries, Mohsin Aziz Sb."],["2023–24","Best Regional Sales Manager – National Level","National-level recognition for top regional performance."],["2023","SMART Sales App Project Lead","Head Office digital transformation initiative."],["2026","SalesPulse AI Analytics System Creator","Created using Gemini AI Studio for Brand, SKU, Order Booker and route-level tracking."],["2019–20","National Champion ZSM Award","National Champion recognition."],["2018","Billion Sales Achievement Team","Member of the Billion Sales Achievement Team."]];
const nav=["About","Focus","Work","Career","Recognition","Education","Contact"];
export function PortfolioShell(){
 const {theme,profile,setTheme,setProfile}=useTheme(); const [menu,setMenu]=useState(false);
 return <div className="site"><LoadingScreen/><Scene/><header className="nav"><a className="brand" href="#top">AMJID<span>/26</span></a><nav className={menu?"nav-links open":"nav-links"}>{nav.map(n=><a key={n} href={"#"+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}</a>)}</nav><div className="controls"><select value={profile} onChange={e=>setProfile(e.target.value as any)}><option value="gravity">Profile · Gravity</option><option value="editorial">Profile · Editorial</option><option value="cinematic">Profile · Cinematic</option></select><select value={theme} onChange={e=>setTheme(e.target.value as any)}><option value="neumorphic">Theme · Neumorphic</option><option value="light">Theme · Light</option><option value="dark">Theme · Dark</option><option value="cinematic">Theme · Cinematic</option></select></div><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button></header>
<main id="top"><section className="hero"><div><p className="eyebrow">MUHAMMAD AMJID · {profile.toUpperCase()} PROFILE</p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}>Sales <i>with</i><br/><span>purpose.</span></motion.h1><p className="hero-text">Senior FMCG Sales Leader with 15+ years across General Trade, Route-to-Market, distribution, forecasting, field-force leadership and practical digital transformation.</p><div className="hero-tags"><b>45+ Distributors</b><b>25% Detergent Share</b><b>#1 among 6 RSMs</b></div><div className="hero-actions"><a className="btn primary" href="#work">Explore work ↗</a><a className="btn" href={resume}>Resume ↗</a></div></div><div className="portrait-card"><div className="portrait-glow"/><img src={img} alt="Muhammad Amjid"/><span className="portrait-code">01 / 03<br/>NORTH PAKISTAN</span></div></section>
<section id="about" className="section"><div className="section-kicker">01 / ABOUT</div><div className="split"><h2>Commercial growth<br/><em>with field reality.</em></h2><div><p className="lead">I connect sales leadership, distribution discipline and useful technology.</p><p>Forecasting, demand planning, numeric and weighted distribution, retail execution, distributor performance and digital sales systems.</p></div></div><div className="metric-grid"><div><strong>15+</strong><span>Years in FMCG</span></div><div><strong>45+</strong><span>Distributors managed</span></div><div><strong>25%</strong><span>Detergent category share</span></div><div><strong>2009→</strong><span>Career start</span></div></div></section>
<section id="focus" className="section"><div className="section-kicker">02 / FOCUS</div><h2>Systems that make<br/><em>execution clearer.</em></h2><div className="card-grid">{[["01","Sales Leadership","Regional strategy, forecasting, targets, distributor performance and field teams."],["02","RTM & Distribution","Coverage, availability, numeric and weighted distribution, route optimization."],["03","Sales Analytics","Brand, SKU, Order Booker and route-level reporting with KPI visibility."],["04","Digital Transformation","Sales automation, field-force tracking and practical digital workflows."]].map(x=><article className="glass-card" key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="work" className="section"><div className="section-kicker">03 / SELECTED WORK</div><div className="work-head"><h2>Sales ×<br/><em>technology.</em></h2><p>Digital systems built around real commercial problems. Sensitive implementation details stay private.</p></div><div className="work-grid"><article className="work-card large"><small>01 / SALES TRANSFORMATION</small><h3>SMART<br/>SALES</h3><p>Real-time sales tracking, GPS monitoring, attendance and KPI dashboards.</p><span>CASE STUDY ↗</span></article><article className="work-card"><small>02 / AI ANALYTICS</small><h3>SALESPULSE<br/><em>AI</em></h3><p>Brand, SKU, OB and route-level performance tracking using Gemini AI Studio.</p><span>PRIVATE SYSTEM ↗</span></article><article className="work-card gold"><small>03 / DIGITAL COMMERCE</small><h3>BAZAR360<br/><em>.ONLINE</em></h3><p>Automotive marketplace and online ecosystem, under development.</p><a href="https://bazar360.online/" target="_blank" rel="noreferrer">OPEN PLATFORM ↗</a></article></div></section>
<section id="career" className="section"><div className="section-kicker">04 / CAREER</div><h2>2009 <em>→</em> Present</h2><div className="timeline">{jobs.map((j,i)=><article key={j[1]}><span>{j[0]}</span><div><h3>{j[1]}</h3>{j[3]?<a href={j[3]} target="_blank" rel="noreferrer">{j[2]} ↗</a>:<b>{j[2]}</b>}</div><small>0{i+1}</small></article>)}</div></section>
<section id="recognition" className="section"><div className="section-kicker">05 / RECOGNITION</div><h2>Recognition for<br/><em>measurable impact.</em></h2><div className="award-grid">{awards.map(a=><article key={a[0]+a[1]}><span>{a[0]}</span><div><h3>{a[1]}</h3><p>{a[2]}</p></div></article>)}</div></section>
<section id="education" className="section"><div className="section-kicker">06 / EDUCATION & SKILLS</div><div className="split"><div><h2>Academic<br/><em>background.</em></h2><div className="edu-list">{[["MBA (Executive)","Gomal University","2018–2020"],["MA Islamic Studies","Bacha Khan University","2018"],["BA","University of Peshawar","2015–2016"],["DAE Electrical","BTE KPK","2004–2007"],["SSC","BISE Peshawar","2004"]].map(e=><div key={e[0]}><b>{e[0]}</b><span>{e[1]} · {e[2]}</span></div>)}</div></div><div><h2>Core<br/><em>skills.</em></h2><div className="skills">{["FMCG Sales Systems","Sales Forecasting","Demand Planning","CRM","Excel Advanced Reporting","AI Analytics","Gemini AI Studio","KPI Dashboards","RTM Optimization","Numeric Distribution","Weighted Distribution","Retail Execution","Distributor Management","Field Force Leadership"].map(s=><span key={s}>{s}</span>)}</div></div></div></section>
<section id="contact" className="contact"><div className="section-kicker">07 / CONTACT</div><h2>Let's<br/><em>connect.</em></h2><p>Open to meaningful commercial opportunities, leadership discussions and digital sales projects.</p><div className="contact-links"><a href="mailto:amjid.psh@gmail.com">Email ↗</a><a href="https://www.linkedin.com/in/amjid1988/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/AmjidOfficial/" target="_blank" rel="noreferrer">GitHub ↗</a><a href={resume}>Resume ↗</a></div></section></main><footer><span>MUHAMMAD AMJID</span><span>SALES · DATA · TECHNOLOGY · © 2026</span></footer></div>}